spring:
  redis:
    host: localhost
    password: 123456
    port: 6379
    ttl: 30

zuul:
  prefix: /api
  routes:
    greeting-service:
      path: /hello-world/**
      url: forward:/hello-world

  ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      greeting-service:
        - limit: 1
          refresh-interval: 10
          type:
            - origin

  strip-prefix: true